### ISSUE TITLE
Module parse failed: node_modules/react-native-web-webview/src/index.js Unexpected token (6:22)

### ISSUE THREAD

**Issue by dgoenka** [react-native-web-community/react-native-web-webview#15]
I have been trying to integrate react-native-web-webview. I have added the rule like so in my webpack.config:

```
...
module.exports = {
...
  module: {
      ...
        rules:[
            {
                test: /postMock.html$/,
                use: {
                    loader: 'file-loader',
                    options: {
                        name: '[name].[ext]',
                    },
                },
            }
        ],
      ...
```

Since I want to try and have a single code base, I'm importing (specifically, `require`ing) the module like this:

```
const WebView = (Platform.OS === 'web') ?
    require("react-native-web-webview") :
    require("react-native").WebView;
/*
I couldn't find a way to use "imports" based on decisions, but do tell if this is still wrong. Because 
I'm using "react-native-web-webview" directly, I didn't alias that.
*/
```
The `render()` function returns something like this:

```
        <WebView
            source={{uri: url}}
            onMessage={(event) => console.log(event.nativeEvent.data)}
            style={styles.web_view}
        />
```
Please tell me where I might be going wrong, because now for the web version (only) I keep getting this error:

```
Error in ./~/react-native-web-webview/src/index.js
Module parse failed: /Users/divyanshgoenka/ReactNativeProjects/ReactNativeUniversal/node_modules/react-native-web-webview/src/index.js Unexpected token (6:22)
You may need an appropriate loader to handle this file type.
```

**Comment by Hex-001** [comment]
If you have a babelLoaderConfiguration rule try adding 

`path.resolve(appDirectory, 'node_modules/react-native-web-webview'),`

into the include array. This should resolve the error.

**Comment by yarra2296** [comment]
I tried adding it But it is showing the same module Error.

**Comment by yarra2296** [comment]
Problem I am facing in the Web --->bundle.web.js:18263 ../node_modules/react-native-web-webview/src/index.js
Module parse failed: Unexpected token (6:22)
You may need an appropriate loader to handle this file type.
| 
| export default class extends Component {
|   static defaultProps = {
|     scrollEnabled: true,
|   };
 @ ../app/screens/PayTM.js 1:1101-1136
 @ ../app/index.js
 @ ../app/index.web.js
 @ multi ../node_modules/webpack-dev-server/client?http://0.0.0.0:8082 babel-polyfill ../app/index.web.js
errors @ bundle.web.js:18263
onmessage @ bundle.web.js:20204
EventTarget.dispatchEvent @ bundle.web.js:20384
(anonymous) @ bundle.web.js:21097
SockJS._transportMessage @ bundle.web.js:21095
EventEmitter.emit @ bundle.web.js:20300
WebSocketTransport.ws.onmessage @ bundle.web.js:23171

**Comment by Minishlink** [comment]
Please try with v0.2.7.
