### ISSUE TITLE
We are getting an Error while using the following Component for web.

### ISSUE THREAD

**Issue by yarra2296** [react-native-web-community/react-native-web-webview#17]
This is the Error I am getting while trying to Run React-native-web in Website. I don't know, I thought this component is for Website. But I am facing many issues while Using the following Component with the Web Version. Please Go through the problem & Do the needful.

Thank you,

bundle.web.js:106913 Uncaught Error: Module parse failed: Unexpected token (107:12)
You may need an appropriate loader to handle this file type.
|     if (this.props.newWindow) {
|         return (
|             <View style={styles.loadingContainer}>
|                 <ActivityIndicator/>
|             </View>
    at Object.<anonymous> (bundle.web.js:106913)
    at __webpack_require__ (bundle.web.js:20)
    at Object.<anonymous> (bundle.web.js:106201)
    at __webpack_require__ (bundle.web.js:20)
    at Object.module.exports.createNavigationContainer (bundle.web.js:55481)
    at __webpack_require__ (bundle.web.js:20)
    at Object.<anonymous> (bundle.web.js:32306)
    at __webpack_require__ (bundle.web.js:20)
    at Object.<anonymous> (bundle.web.js:18089)
    at __webpack_require__ (bundle.web.js:20)
(anonymous) @ bundle.web.js:106913
__webpack_require__ @ bundle.web.js:20
(anonymous) @ bundle.web.js:106201
__webpack_require__ @ bundle.web.js:20
module.exports.createNavigationContainer @ bundle.web.js:55481
__webpack_require__ @ bundle.web.js:20
(anonymous) @ bundle.web.js:32306
__webpack_require__ @ bundle.web.js:20
(anonymous) @ bundle.web.js:18089
__webpack_require__ @ bundle.web.js:20
(anonymous) @ bundle.web.js:63
(anonymous) @ bundle.web.js:66
bundle.web.js:18257 [WDS] Errors while compiling. Reload prevented.
errors @ bundle.web.js:18257
onmessage @ bundle.web.js:20204
EventTarget.dispatchEvent @ bundle.web.js:20384
(anonymous) @ bundle.web.js:21097
SockJS._transportMessage @ bundle.web.js:21095
EventEmitter.emit @ bundle.web.js:20300
WebSocketTransport.ws.onmessage @ bundle.web.js:23171
bundle.web.js:18263 ../node_modules/react-native-web-webview/src/index.js
Module parse failed: Unexpected token (107:12)
You may need an appropriate loader to handle this file type.
|     if (this.props.newWindow) {
|         return (
|             <View style={styles.loadingContainer}>
|                 <ActivityIndicator/>
|             </View>
 @ ../app/screens/PayTM.js 1:1101-1136
 @ ../app/index.js
 @ ../app/index.web.js
 @ multi ../node_modules/webpack-dev-server/client?http://0.0.0.0:8082 babel-polyfill ../app/index.web.js
errors @ bundle.web.js:18263
onmessage @ bundle.web.js:20204
EventTarget.dispatchEvent @ bundle.web.js:20384
(anonymous) @ bundle.web.js:21097
SockJS._transportMessage @ bundle.web.js:21095
EventEmitter.emit @ bundle.web.js:20300
WebSocketTransport.ws.onmessage @ bundle.web.js:23171

**Comment by Minishlink** [comment]
Hello,
make sure to compile the lib through `babel-preset-react-native`. Is your webpack config correct ? See this [example](https://github.com/Minishlink/DailyScrum/blob/master/web/webpack.config.babel.js#L21) :)

**Comment by Minishlink** [comment]
Please try with v0.2.7.
