### ISSUE TITLE
Can't resolve './postMock.html

### ISSUE THREAD

**Issue by sunny-wanghaiqing** [react-native-web-community/react-native-web-webview#19]
hello, I have a question ,can you help me?

**ERROR in ./node_modules/react-native-web-webview/dist/index.js
Module not found: Error: Can't resolve './postMock.html' in '...'**

I  have already set rules at webpack, but do not works.
`const rule = {
  test: /postMock.html$/,
  use: {
    loader: 'file-loader',
    options: {
      name: '[name].[ext]',
    },
  },
};`

**Comment by RajeshBatth** [comment]
any updates on this, I'm also facing this issue
