### ISSUE TITLE
Event onMessage fired many times after the first event

### ISSUE THREAD

**Issue by adrianicv** [react-native-web-community/react-native-web-webview#2]
In the onMessage example, if the button is pressed, the message appears in the console as expected. But after that, all events captured by the WindowsListener are also printed in the console.

Steps to reproduce:

1. Enter in the onMessage in the storybook example and press send message.
2. Change to any other examples and you will see that each time you change of example a event is captured and printed in the console. 

Moreover, each time you pressed the button, one more EventListener is activated. So, the number of messages increase "n" times, where "n" is the number of EventListener active.

**Comment by piranna** [comment]
Problem is at https://github.com/react-native-web-community/react-native-web-webview/blob/8a0c48f1e85496c0b2fb4a255592e9b101383d39/src/index.js#L9-L11, the `message` listener is not unregistered on unload, that's why they are later captured and when loading several times messages get duplicated.

**Comment by piranna** [comment]
I think `addEventListener()` should be called instead on `componentDidMount()` and use `removeEventListener()` at `componentWillUnmount()`.

**Comment by Minishlink** [comment]
Thanks for the feedback !
It should indeed be handled in componentDidMount / componentWillUnmount.
If you're feeling like doing a PR you're very welcome ! Otherwise I'll try to find some time next week :)

**Comment by piranna** [comment]
> If you're feeling like doing a PR you're very welcome

[Done](https://github.com/react-native-web-community/react-native-web-webview/pull/3).

**Comment by Minishlink** [comment]
Thanks a lot @piranna! This is fixed in [v0.1.0](https://github.com/react-native-web-community/react-native-web-webview/releases/tag/v0.1.0).

**Comment by piranna** [comment]
> Thanks a lot @piranna! This is fixed in v0.1.0.

You are welcome :-)
