### ISSUE TITLE
export default WebView

### ISSUE THREAD

**Issue by lejsue** [react-native-web-community/react-native-web-webview#29]
Hi, thanks for this good package to help me implement webview on react-native app and react-native-web app.
I saw that it is also export default WebView in the react-native-webview (https://github.com/react-native-community/react-native-webview/blob/b482bbd3a38d75e44830f68cda9053ef2a7958b6/index.js#L4)
could you also help to add "export default WebView" in index.js?

**Comment by Minishlink** [comment]
Hi, thanks for the feedback, it's now available in 1.0.2 :)
