### ISSUE TITLE
Show `POST` data on embedded iframe

### ISSUE THREAD

**Issue by piranna** [react-native-web-community/react-native-web-webview#4]
Seems it's possible to redirect the content of a `POST` request done by a form by using the `target` field by [pointing it to the iframe](https://css-tricks.com/snippets/html/post-data-to-an-iframe/), so we could do the `POST` request and embed its content instead of showing it in a new window. Also, doing it that way we could render the request form hidden on the main page, so there's no need to open a new window for this thing too, making the component both fully standalone and transparent to the user.

**Comment by piranna** [comment]
Or maybe by doing a `fetch` request and `innerHtml` with the returned content, we could also use any other method or content type, too :-)

**Comment by Minishlink** [comment]
Thanks for the input!
FYI, opening in a new window is necessary most of the time, because most websites have a no-CORS policy or set X-Frame-Options to true.
[v0.1.0](https://github.com/react-native-web-community/react-native-web-webview/releases/tag/v0.1.0) supports every kind of requests when you set the `newWindow` prop to false.

**Comment by piranna** [comment]
> FYI, opening in a new window is necessary most of the time, because most websites have a no-CORS policy or set X-Frame-Options to true.

Interesting point, didn't know about that. In that case, maybe it would be possible to open a minified window and later close it after content is put inside the iframe, or something else...

**Comment by Minishlink** [comment]
I added support in [v0.2.0](https://github.com/react-native-web-community/react-native-web-webview/releases/tag/v0.2.0) for setting the new window's internal name and features, that way you'll be able to specify the size of the window and so on. Note that browser support can [vary a lot](https://developer.mozilla.org/fr/docs/Web/API/Window/open).
