### ISSUE TITLE
Why? Readme doesn’t explain why.

### ISSUE THREAD

**Issue by redbar0n** [react-native-web-community/react-native-web-webview#65]
A genuine question, since when I come across a library the first question on my mind is always: 

Why does it exist? To judge if I have, or could have, the same need.

So it would be nice if the Readme could explain briefly at the top:

What was the original motivation/purpose for this library? Why would one want a React Native Web (RNW) implementation of WebView?

I am currently a bit bewildered, so maybe the discussion in this issue could clarify these questions as well:

Isn’t the React Native WebView sufficient? Why does one need a WebView on the Web? Doesn’t RNW default to showing Web elements on web, like `<div>` instead of `<View>`, for instance? What does a WebView add over that?

**Comment by Minishlink** [comment]
Hi, my primary use case is having an existing React Native app and wanting to port the app (or a part of) to the web with the same code. Typically when doing this, you start by making everything work in a functional manner (native modules being the most time-consuming), and then you fine tune to adapt for the web. Sometimes you want to move fast or the WebViews used in the app have low importance for the user, and you can use this package to "unblock" the feature.
As stated [here](https://github.com/necolas/react-native-web/issues/161#issuecomment-333475862) though, a webview (or an iframe for that matter) usually makes for poor UX on the web, so you might want to fine tune this afterwards depending on your project's and users' priorities.

**Comment by redbar0n** [comment]
Thanks for clearing this up! It makes a lot more sense now. So it’s a WebView-to-iFrame replacement/shim to make the React Native WebViews compatible (in a drop-in manner) with RNW out of the box (before one starts rewriting the code to not use the WebView/iFrame).
