### ISSUE TITLE
Disable scrolling in webview

### ISSUE THREAD

**Issue by adrianicv** [react-native-web-community/react-native-web-webview#8]
Hi,

it should be possible to pass as a prop the `scrolling` option for the iframe to disable scrolling. It may be look like:
`
<Webview src='http://url.com scrolling={false}>
`
And include in the iframe `scrolling="no"` if `false` is passed as the value of the `scrolling` prop.

Thank you in advance.

**Comment by remon-georgy** [comment]
I'm sure the maintainer won't mind reviewing a PR ;). Luckily the change could be as trivial as #5 .

Regarding property name. How about calling it `scrollEnabled` to be inline with the [React native](https://facebook.github.io/react-native/docs/webview.html#scrollenabled) component?

**Comment by adrianicv** [comment]
Here is the PR :slightly_smiling_face:  #9

**Comment by Minishlink** [comment]
Thanks @adrianicv! It's live in 0.2.2 :)
